### ISSUE TITLE
org.gnome.Platform branch 43 is end-of-life

### ISSUE THREAD

**Issue by VaiTon** [flathub/org.gnome.PowerStats#11]
```
~> sudo flatpak update 
Looking for updates…

Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.gnome.PowerStats

```

**Comment by hughsie** [comment]
I think it needs to bump the runtime -- and we also need to bump the upower version. Any help with that very welcome.

**Comment by wjt** [comment]
I started looking at this. libgudev in shared-modules needs an update which I submitted as https://github.com/flathub/shared-modules/pull/279.

**Comment by wjt** [comment]
The next stumbling block is to tell upower not to install its udev rules.
